# game/constants.py
from .enums import CardType

"""Community Chest cards for Monopoly"""

CHANCE_CARDS = [
    {
        "id": 1,
        "name": "Advance to GO",
        "description": "Advance to GO (Collect $200)",
        "type": CardType.ADVANCE_TO_GO,
        "amount": 200,
        "action": "move_to_go",
        "position": 0,
    },
    {
        "id": 2,
        "name": "Advance to Illinois Avenue",
        "description": "Advance to Illinois Avenue",
        "type": CardType.ADVANCE_TO_PROPERTY,
        "amount": 0,
        "action": "advance_to_property",
        "position": 24,
        "property_name": "Illinois Avenue",
    },
    {
        "id": 4,
        "name": "Bank Dividend",
        "description": "Bank pays you dividend of $50",
        "type": CardType.COLLECT_MONEY,
        "amount": 50,
        "action": "collect_money",
    },
    {
        "id": 5,
        "name": "Go Back 3 Spaces",
        "description": "Go back three spaces",
        "type": CardType.MOVE_BACK,
        "amount": 0,
        "action": "move_back",
        "spaces": 3,
    },
    {
        "id": 6,
        "name": "Go to Jail",
        "description": "Go directly to Jail",
        "type": CardType.GO_TO_JAIL,
        "amount": 0,
        "action": "go_to_jail",
        "position": 10,
    },
    {
        "id": 7,
        "name": "General Repairs",
        "description": "Make general repairs on all your property: $25 per house, $100 per hotel",
        "type": CardType.GENERAL_REPAIRS,
        "amount": 0,
        "action": "general_repairs",
        "house_cost": 25,
        "hotel_cost": 100,
    },
    {
        "id": 8,
        "name": "Pay Poor Tax",
        "description": "Pay poor tax of $15",
        "type": CardType.PAY_MONEY,
        "amount": 15,
        "action": "pay_money",
    },
    {
        "id": 10,
        "name": "Take a Walk on the Boardwalk",
        "description": "Take a walk on the Boardwalk",
        "type": CardType.ADVANCE_TO_PROPERTY,
        "amount": 0,
        "action": "advance_to_property",
        "position": 39,
        "property_name": "Boardwalk",
    },
    {
        "id": 11,
        "name": "Elected Chairman",
        "description": "You have been elected Chairman of the Board. Pay each player $50",
        "type": CardType.PAY_EACH_PLAYER,
        "amount": 50,
        "action": "pay_each_player",
    },
    {
        "id": 12,
        "name": "Building Loan Matures",
        "description": "Your building loan matures. Collect $150",
        "type": CardType.COLLECT_MONEY,
        "amount": 150,
        "action": "collect_money",
    },
    {
        "id": 13,
        "name": "Crossword Competition",
        "description": "You won a crossword competition. Collect $100",
        "type": CardType.COLLECT_MONEY,
        "amount": 100,
        "action": "collect_money",
    },
    {
        "id": 14,
        "name": "Bank Error in Your Favor",
        "description": "Bank error in your favor. Collect $200",
        "type": CardType.COLLECT_MONEY,
        "amount": 200,
        "action": "collect_money",
    },
    {
        "id": 15,
        "name": "Get Out of Jail Free",
        "description": "Get Out of Jail Free - Keep this card",
        "type": CardType.GET_OUT_OF_JAIL,
        "amount": 0,
        "action": "get_out_of_jail",
    },
    {
        "id": 16,
        "name": "Pay School Fees",
        "description": "Pay school fees of $50",
        "type": CardType.PAY_MONEY,
        "amount": 50,
        "action": "pay_money",
    },
]

COMMUNITY_CHEST_CARDS = [
    {
      "id": 1,
      "name": "Advance to GO",
      "description": "Advance to GO (Collect $200)",
      "type": CardType.ADVANCE_TO_GO,
      "amount": 200,
    },
    {
      "id": 2,
      "name": "Bank Error",
      "description": "Bank error in your favor. Collect $200",
      "type": CardType.COLLECT_MONEY,
      "amount": 200,
    },
    {
      "id": 3,
      "name": "Doctor's Fee",
      "description": "Doctor's fee. Pay $50",
      "type": CardType.PAY_MONEY,
      "amount": 50,
    },
    {
      "id": 4,
      "name": "Stock Sale",
      "description": "From sale of stock you get $50",
      "type": CardType.COLLECT_MONEY,
      "amount": 50,
    },
    {
        "id": 5,
        "name": "Get Out of Jail Free",
        "description": "Get Out of Jail Free - Keep this card",
        "type": CardType.GET_OUT_OF_JAIL,
        "amount": 0,
    },
    {
        "id": 6,
        "name": "Go to Jail",
        "description": "Go to Jail",
        "type": CardType.GO_TO_JAIL,
        "amount": 0,
    },
    {
        "id": 7,
        "name": "Grand Opera Night",
        "description": "Grand Opera Night. Collect $50 from every player",
        "type": CardType.COLLECT_FROM_ALL,
        "amount": 50,
    },
    {
        "id": 8,
        "name": "Holiday Fund",
        "description": "Holiday fund matures. Receive $100",
        "type": CardType.COLLECT_MONEY,
        "amount": 100,
    },
    {
        "id": 9,
        "name": "Tax Refund",
        "description": "Income tax refund. Collect $20",
        "type": CardType.COLLECT_MONEY,
        "amount": 20,
    },
    {
        "id": 10,
        "name": "Birthday",
        "description": "It's your birthday! Collect $10 from each player",
        "type": CardType.COLLECT_FROM_ALL,
        "amount": 10,
    },
    {
        "id": 11,
        "name": "Life Insurance",
        "description": "Life insurance matures. Collect $100",
        "type": CardType.COLLECT_MONEY,
        "amount": 100,
    },
    {
        "id": 12,
        "name": "Hospital Fees",
        "description": "Pay hospital fees of $100",
        "type": CardType.PAY_MONEY,
        "amount": 100,
    },
    {
        "id": 13,
        "name": "School Fees",
        "description": "Pay school fees of $50",
        "type": CardType.PAY_MONEY,
        "amount": 50,
    },
    {
        "id": 14,
        "name": "Consultancy Fee",
        "description": "Receive $25 consultancy fee",
        "type": CardType.COLLECT_MONEY,
        "amount": 25,
    },
    {
        "id": 15,
        "name": "Street Repairs",
        "description": "You are assessed for street repairs: $40 per house, $115 per hotel",
        "type": CardType.STREET_REPAIRS,
        "amount": 0,
    },
    {
        "id": 16,
        "name": "Beauty Contest",
        "description": "You have won second prize in a beauty contest. Collect $10",
        "type": CardType.COLLECT_MONEY,
        "amount": 10,
    },
]

# Card type metadata for display
CARD_TYPE_METADATA = {
    CardType.COLLECT_MONEY: {
        'emoji': '💰',
        'color': '#48bb78',
        'label': '💰 Collect Money',
        'is_positive': True,
    },
    CardType.PAY_MONEY: {
        'emoji': '💸',
        'color': '#fc8181',
        'label': '💸 Pay Money',
        'is_positive': False,
    },
    CardType.COLLECT_FROM_ALL: {
        'emoji': '🎁',
        'color': '#4fd1c5',
        'label': '🎁 Collect from All',
        'is_positive': True,
    },
    CardType.PAY_EACH_PLAYER: {
        'emoji': '💸',
        'color': '#fc8181',
        'label': '💸 Pay Each Player',
        'is_positive': False,
    },
    CardType.ADVANCE_TO_GO: {
        'emoji': '🏃',
        'color': '#63b3ed',
        'label': '🏃 Advance to GO',
        'is_positive': True,
    },
    CardType.ADVANCE_TO_PROPERTY: {
        'emoji': '🏠',
        'color': '#b794f4',
        'label': '🏠 Advance to Property',
        'is_positive': True,
    },
    CardType.ADVANCE_TO_RAILROAD: {
        'emoji': '🚂',
        'color': '#f6ad55',
        'label': '🚂 Advance to Railroad',
        'is_positive': True,
    },
    CardType.MOVE_BACK: {
        'emoji': '🔙',
        'color': '#fc8181',
        'label': '🔙 Move Back',
        'is_positive': False,
    },
    CardType.GO_TO_JAIL: {
        'emoji': '🔒',
        'color': '#fc8181',
        'label': '🔒 Go to Jail',
        'is_positive': False,
    },
    CardType.GET_OUT_OF_JAIL: {
        'emoji': '🆓',
        'color': '#b794f4',
        'label': '🆓 Get Out of Jail',
        'is_positive': True,
    },
    CardType.STREET_REPAIRS: {
        'emoji': '🔧',
        'color': '#fc8181',
        'label': '🔧 Street Repairs',
        'is_positive': False,
    },
    CardType.GENERAL_REPAIRS: {
        'emoji': '🔧',
        'color': '#fc8181',
        'label': '🔧 General Repairs',
        'is_positive': False,
    },
}