from django.db import models

class CardType(models.TextChoices):
    # Money cards
    COLLECT_MONEY = 'COLLECT_MONEY'
    PAY_MONEY = 'PAY_MONEY'
    COLLECT_FROM_ALL = 'COLLECT_FROM_ALL'
    PAY_EACH_PLAYER = 'PAY_EACH_PLAYER'
    
    # Movement cards
    ADVANCE_TO_GO = 'ADVANCE_TO_GO'
    ADVANCE_TO_PROPERTY = 'ADVANCE_TO_PROPERTY'
    ADVANCE_TO_RAILROAD = 'ADVANCE_TO_RAILROAD'
    MOVE_BACK = 'MOVE_BACK'
    GO_TO_JAIL = 'GO_TO_JAIL'
    
    # Special cards
    GET_OUT_OF_JAIL = 'GET_OUT_OF_JAIL'
    STREET_REPAIRS = 'STREET_REPAIRS'
    GENERAL_REPAIRS = 'GENERAL_REPAIRS'

class SquareType(models.TextChoices):
    GO = "GO"
    PROPERTY = "PROPERTY"
    TAX = "TAX"
    GO_TO_JAIL = "GO_TO_JAIL"
    CHANCE = "CHANCE"
    COMMUNITY_CHEST = "COMMUNITY_CHEST"
    RAIL_ROAD="RAIL_ROAD"
    UTILITY="UTILITY"

    