# Generated by Django 6.0.6 on 2026-06-25 07:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='player',
            name='is_in_jail',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='money',
            field=models.IntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
