# Generated by Django 6.0.6 on 2026-06-25 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_game_max_players_game_min_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_games', to='game.player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='state',
            field=models.CharField(choices=[('WT', 'Waiting for Players'), ('PL', 'Playing'), ('FI', 'Finished'), ('CA', 'Cancelled')], default='WT', max_length=2),
        ),
    ]
