# Generated by Django 6.0.6 on 2026-06-25 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_game_created_by_alter_game_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='number_of_turns',
            new_name='turn_number',
        ),
    ]
