# Generated by Django 6.0.6 on 2026-07-04 08:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_rename_number_of_turns_game_turn_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color_code', models.CharField(help_text='Hex color code', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Square',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(39)])),
                ('name', models.CharField(max_length=100)),
                ('square_type', models.CharField(choices=[('GO', 'Go'), ('PR', 'Property'), ('JA', 'Jail'), ('FP', 'Free Parking'), ('GJ', 'Go to Jail'), ('CH', 'Chance'), ('CC', 'Community Chest'), ('TA', 'Tax'), ('RR', 'Railroad'), ('UT', 'Utility')], max_length=2)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('rent', models.IntegerField(blank=True, null=True)),
                ('tax_amount', models.IntegerField(blank=True, null=True)),
                ('color_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.colorgroup')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('houses', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('is_mortgaged', models.BooleanField(default=False)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='game.game')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='game.player')),
                ('square', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property', to='game.square')),
            ],
        ),
    ]
