# Generated by Django 6.0.6 on 2026-08-07 07:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_colorgroup_square_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='hotels',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
