# Generated by Django 6.0.6 on 2026-08-15 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_property_hotels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='created_by',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, related_name='created_games', to='game.player'),
            preserve_default=False,
        ),
    ]
