# Generated by Django 6.0.6 on 2026-08-17 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_alter_game_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='hotels',
        ),
    ]
