# Generated by Django 6.0.6 on 2026-08-17 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_remove_property_hotels'),
    ]

    operations = [
        migrations.AddField(
            model_name='square',
            name='house_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
