# Generated by Django 6.0.6 on 2026-09-08 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_square_house_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='square',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property', to='game.square'),
        ),
        migrations.AlterUniqueTogether(
            name='property',
            unique_together={('square', 'game')},
        ),
    ]
