# Generated by Django 6.0.6 on 2026-09-08 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_alter_property_square_alter_property_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='square',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property', to='game.square'),
        ),
    ]
