# Generated by Django 6.0.6 on 2026-09-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_alter_property_square'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='get_out_of_jail_cards',
            field=models.IntegerField(default=0),
        ),
    ]
