# Generated by Django 6.0.6 on 2026-09-28 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_player_get_out_of_jail_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='doubles_count',
            field=models.IntegerField(default=0),
        ),
    ]
