# Generated by Django 6.0.6 on 2026-09-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_player_doubles_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='has_rolled',
            field=models.BooleanField(default=False),
        ),
    ]
